#!/usr/bin/env python
# encoding: utf-8

import os
import re
import sys
import json
import argparse
import stat
from pprint import pformat

PROFILE_D_SCRIPT = '/etc/profile.d/virtualcandy.sh'


class PipLock(object):

    def __init__(self, fd=None):
        self._fd = fd or open(os.path.join(os.getcwd(), 'Pipfile.lock'), 'r')
        self._pf = json.load(self._fd)
        self._def_key = 'default'
        self._dev_key = 'develop'

    def _to_freeeze_list(self, pkgs):
        res = []
        for k, v in pkgs.items():
            if isinstance(v, dict) and v.get('version'):
                res.append("%s%s" % (k, v.get('version')))

        return res

    def has(self, pkg_name):
        return self.has_def(pkg_name) or self.has_dev(pkg_name)

    def has_dev(self, pkg_name):
        return pkg_name in self.develop

    def has_def(self, pkg_name):
        return pkg_name in self.default

    @property
    def default(self):
        return self._pf.get(self._def_key, {})

    @property
    def default_freeze(self):
        return self._to_freeeze_list(self.default)

    @property
    def develop(self):
        return self._pf.get(self._dev_key, {})

    @property
    def develop_freeze(self):
        return self._to_freeeze_list(self.develop)

    def __str__(self):
        return pformat(self._pf)

    def __repr__(self):
        return pformat(self._pf)


def freeze(args, pl):
    if args.dev:
        print('\n'.join(pl.develop_freeze))
    else:
        print('\n'.join(pl.default_freeze))


def pkgs(args, pl):
    pkg = args.pkg[0]
    res = ''

    if pl.has_def(pkg):
        res = 'default'
    elif pl.has_dev(pkg):
        res = 'develop'

    print(res)


def install(args, pl):
    from distutils.sysconfig import get_python_lib
    plibs = os.path.join(get_python_lib(), 'virtualcandy', 'lib')

    # Kind of stupid and only supports zsh or bash
    shell = os.path.basename(os.environ.get('SHELL'))

    ext = 'sh'
    if args.zsh:
        ext = 'zsh'
    elif not args.sh:
        shell = os.path.basename(os.environ.get('SHELL'))
        if shell == 'zsh':
            ext = shell

    incl = os.path.join(plibs, f'virtualcandy.{ext}')

    home = os.path.expanduser('~')
    src = os.path.join(home, '.bashrc')
    if ext == 'zsh':
        src = os.path.join(home, '.zshrc')

    shell_snip = (
        f'if [[ -f "{incl}" ]]; then\n'
        f'    . "{incl}"\n'
        'fi\n'
    )

    if args.system:
        # install the /etc/profile.d/script
        try:
            with open(PROFILE_D_SCRIPT, 'w') as fd:
                fd.write(shell_snip)

            os.chmod(PROFILE_D_SCRIPT, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH | stat.S_IWUSR)
        except PermissionError as e:
            print("You don't have permission to perform a system install.")
            print("Retry the installation as root, or re-run the command with `sudo`:")
            print('\tsudo ' + ' '.join(sys.argv))
            sys.exit(1)

    print(f'\n# Add the following 3 lines into your {src} file')
    print(shell_snip)


def main(parser):
    args = parser.parse_args()

    try:
        pl = PipLock(fd=args.lock_file)
    except Exception:
        pl = None

    if hasattr(args, 'func'):
        args.func(args, pl)
        sys.exit(0)

    parser.print_help()
    sys.exit(1)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Virtual Candy packaging helper')
    parser.add_argument('--dev', action='store_true',
                        help='Apply operation as development packaging'
                        )
    parser.add_argument('--lock-file', type=argparse.FileType('r'),
                        help='Specify the path to the lock file'
                        )

    subparsers = parser.add_subparsers()

    parser_freeze = subparsers.add_parser(
        'freeze',
        aliases=['f', 'fr'],
        help="Create 'pip freeze' output from locked packages."
    )
    parser_freeze.add_argument('--freeze', default=True)
    parser_freeze.set_defaults(func=freeze)

    parser_info = subparsers.add_parser(
        'info',
        aliases=['i'],
        help="Get info about a pkg. Currently just reports if a package is default or dev"
    )
    parser_info.add_argument(
        'pkg',
        nargs=argparse.ONE_OR_MORE,
        help="The name of the package to look for info on."
    )
    parser_info.set_defaults(func=pkgs)

    parser_install = subparsers.add_parser(
        'install',
        help="Install the shell code needed for a per user install."
    )
    parser_install.add_argument(
        '--sh', action='store_true',
        help="Install for bash shell"
    )
    parser_install.add_argument(
        '--zsh', action='store_true',
        help="Install for zsh shell"
    )
    parser_install.add_argument(
        '--system', action='store_true',
        help=(
            "Install globaly by creating /etc/profile.d/virtualcandy.sh, "
            "must by done with proper permsissions, \n"
            "\tex: `sudo dpkgs install --system`"
        )
    )
    parser_install.set_defaults(func=install)

    main(parser)
